FROM python:3.10.4

LABEL maintainer="s110810547@student.nqu.edu.tw"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV APP_HOME=/var/www/html/Alzheimer_web
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

ADD requirements.txt $APP_HOME

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

ENTRYPOINT /bin/bash ./start.sh
