# Generated by Django 4.0.3 on 2022-03-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image',
            name='image',
            field=models.ImageField(upload_to='static/upload_images/'),
        ),
    ]
