# Generated by Django 4.0.3 on 2022-03-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_upload_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_image',
            old_name='upload_date',
            new_name='date',
        ),
    ]
