# Generated by Django 4.0.3 on 2022-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_rename_upload_date_upload_image_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
