# Generated by Django 3.2.12 on 2022-04-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_upload_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_image',
            name='tag',
            field=models.CharField(default='NonDmented', max_length=100),
        ),
    ]
