# Generated by Django 4.0.3 on 2022-04-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_upload_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_image',
            name='tag',
            field=models.CharField(default='NonDmented', max_length=50),
        ),
    ]
