# Generated by Django 4.0.3 on 2022-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_upload_image_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image',
            name='tag',
            field=models.CharField(default='NonDmented', max_length=100),
        ),
    ]
