# Generated by Django 3.2.12 on 2022-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_upload_image_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image',
            name='tag',
            field=models.CharField(choices=[('MildDmented', 'MildDmented'), ('ModerateDemented', 'ModerateDmented'), ('NonDemented', 'NonDemented'), ('VeryMildDemented', 'VeryMildDemented'), ('Unknow', 'Unknow')], default='NonDmented', max_length=100),
        ),
    ]
