# Generated by Django 3.2.12 on 2022-05-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_alter_upload_image_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoid', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('pubtime', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('press', models.IntegerField(default=0)),
            ],
        ),
    ]
