# Generated by Django 3.2.12 on 2022-05-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_newsunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsunit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
