# Generated by Django 3.2.12 on 2022-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_alter_newsunit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsunit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
