# Generated by Django 3.2.12 on 2022-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_alter_newsunit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
