# Generated by Django 3.2.12 on 2022-05-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_alter_newsunit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsunit',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='newsunit',
            name='title',
        ),
    ]
